---
title: sundayinc
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  services:
    title: Services
    output: true
    permalink: "/services/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: post
- scope:
    path: ''
    type: services
  values:
    layout: post
future: true
sass:
  sass_dir: _sass
  style: compressed
